// internal/cli/templates/react/src/App.jsx
import { useState, useEffect } from 'react'

function App() {
  const [platform, setPlatform] = useState('')
  const [arch, setArch] = useState('')

  useEffect(() => {
    async function init() {
      const p = await lightshell.system.platform()
      const a = await lightshell.system.arch()
      setPlatform(p)
      setArch(a)
    }
    init()
  }, [])

  return (
    <main>
      <h1>{{TITLE}}</h1>
      <p>Your LightShell + React app is running.</p>
      {platform && <div className="info">{platform}/{arch}</div>}
    </main>
  )
}

export default App

// internal/cli/templates/svelte/src/App.svelte
<script>
  let platform = $state('')
  let arch = $state('')

  async function init() {
    platform = await lightshell.system.platform()
    arch = await lightshell.system.arch()
  }

  $effect(() => {
    init()
  })
</script>

<main>
  <h1>{{TITLE}}</h1>
  <p>Your LightShell + Svelte app is running.</p>
  {#if platform}
    <div class="info">{platform}/{arch}</div>
  {/if}
</main>
